package myforms;

import dao.impl.BookDAOImpl;
import dao.impl.BorrowDAOImpl;
import dao.impl.LibraryCardDAOImpl;
import entities.Book;
import entities.Borrow;
import entities.LibraryCard;
import java.awt.Color;
import java.awt.Font;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
import myclasses.FunctionClass;

/**
 *
 * @author hieu0
 */
public class ManageBorrowForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageGenresForm
     */
    DefaultTableModel dftbl;

    public ManageBorrowForm() {
        initComponents();
        //dftbl = (DefaultTableModel) jTable_User_.getModel();
        // center the form
        this.setLocationRelativeTo(null);

        //display image on the top
        myclasses.FunctionClass func = new FunctionClass();
        func.displayImage(75, 60, "/my_images/user.png", jLabel_FormTitle);

        // add a gray border to the Jpanel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(71, 54, 218));
        jPanel1.setBorder(panelHeaderBorder);

        //customize the Jtable
        jTable_Borrow_.setSelectionBackground(new Color(249, 105, 14));
        jTable_Borrow_.setSelectionForeground(Color.white);
        jTable_Borrow_.setRowHeight(25);
        //jTable_Genres.setShowGrid(true);
        jTable_Borrow_.setBackground(new Color(248, 248, 248));

        //customize the Jtable header row
        jTable_Borrow_.getTableHeader().setBackground(new Color(42, 187, 155));
        jTable_Borrow_.getTableHeader().setForeground(Color.black);
        jTable_Borrow_.getTableHeader().setFont(new Font("Vardana", Font.BOLD, 13));
        jTable_Borrow_.getTableHeader().setOpaque(false);

        //Refresh table
        populateJTableWithBorrow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jButton_Add_ = new javax.swing.JButton();
        jButton_Edit_ = new javax.swing.JButton();
        jButton_Delete_ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_Borrow_ = new javax.swing.JTable();
        jButton_FindById_ = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_BorrowDate = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combo_CardCode = new javax.swing.JComboBox<>();
        txt_ReturnDate = new com.toedter.calendar.JDateChooser();
        combo_Book = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_FormTitle.setBackground(new java.awt.Color(71, 54, 218));
        jLabel_FormTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("       Manage Borrow");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm.setBackground(new java.awt.Color(71, 54, 218));
        jLabel_CloseForm.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel_CloseForm.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_CloseForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm.setText("x");
        jLabel_CloseForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm.setOpaque(true);
        jLabel_CloseForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseFormMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID:");

        txt_Id.setEditable(false);
        txt_Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdActionPerformed(evt);
            }
        });

        jButton_Add_.setBackground(new java.awt.Color(0, 255, 0));
        jButton_Add_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Add_.setForeground(new java.awt.Color(111, 13, 200));
        jButton_Add_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_images/icons8-add-24.png"))); // NOI18N
        jButton_Add_.setText("Add");
        jButton_Add_.setContentAreaFilled(false);
        jButton_Add_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Add_.setOpaque(true);
        jButton_Add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_ActionPerformed(evt);
            }
        });

        jButton_Edit_.setBackground(new java.awt.Color(0, 255, 0));
        jButton_Edit_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Edit_.setForeground(new java.awt.Color(111, 13, 200));
        jButton_Edit_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_images/icons8-update-24.png"))); // NOI18N
        jButton_Edit_.setText("Edit");
        jButton_Edit_.setContentAreaFilled(false);
        jButton_Edit_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Edit_.setOpaque(true);
        jButton_Edit_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Edit_ActionPerformed(evt);
            }
        });

        jButton_Delete_.setBackground(new java.awt.Color(255, 51, 51));
        jButton_Delete_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_Delete_.setForeground(new java.awt.Color(111, 13, 200));
        jButton_Delete_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_images/icons8-delete-24.png"))); // NOI18N
        jButton_Delete_.setText("Delete");
        jButton_Delete_.setContentAreaFilled(false);
        jButton_Delete_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Delete_.setOpaque(true);
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        jTable_Borrow_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_Borrow_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Borrow_MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_Borrow_);

        jButton_FindById_.setBackground(new java.awt.Color(0, 255, 0));
        jButton_FindById_.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton_FindById_.setForeground(new java.awt.Color(111, 13, 200));
        jButton_FindById_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my_images/icons8-search-24.png"))); // NOI18N
        jButton_FindById_.setText("Find by Id");
        jButton_FindById_.setContentAreaFilled(false);
        jButton_FindById_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_FindById_.setOpaque(true);
        jButton_FindById_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_FindById_ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Borrow Date:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Book:");

        txt_BorrowDate.setDateFormatString("dd/MM/yyyy");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Return Date:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Card ID:");

        combo_CardCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_CardCodeActionPerformed(evt);
            }
        });

        txt_ReturnDate.setDateFormatString("dd/MM/yyyy");

        combo_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_BookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jButton_Add_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_CardCode, 0, 170, Short.MAX_VALUE)
                                    .addComponent(combo_Book, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(216, 216, 216)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_BorrowDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ReturnDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                                .addComponent(jButton_Edit_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addComponent(jButton_FindById_)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_CloseForm, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(combo_CardCode, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_BorrowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combo_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Add_)
                            .addComponent(jButton_Edit_)
                            .addComponent(jButton_Delete_)
                            .addComponent(jButton_FindById_)))
                    .addComponent(txt_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseFormMouseClicked

        // Display DashboardForm
        DashboardForm dash_f = new DashboardForm();
        dash_f.setVisible(true);
        
        // close the form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseFormMouseClicked

    private void txt_IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdActionPerformed

    private void jButton_Add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_ActionPerformed
        // add new Use

        List<LibraryCard> listLib = new LibraryCardDAOImpl().getCardList();
        List<Book> listBook = new BookDAOImpl().getListBook();
        Date brD = txt_BorrowDate.getDate();
        Date rtD = txt_ReturnDate.getDate();
        LibraryCard lib = listLib.get(combo_CardCode.getSelectedIndex());
        int cardId = lib.getId();
        Book b = listBook.get(combo_Book.getSelectedIndex());
        int bookId = b.getBookId();
        // check textfield empty or not
        if (brD == null) {
            JOptionPane.showMessageDialog(null, "This field cannot be empty", "Borrow Date", 2);
        } else if (rtD == null) {
            JOptionPane.showMessageDialog(null, "This field cannot be empty", "Return Date", 2);
        } else {
            if (brD.compareTo(rtD)>0) {
                JOptionPane.showMessageDialog(null, "Return Date must be greater than borrow date", "Return Date", 2);
            } else {
                Borrow br = new Borrow();
                br.setCardId(cardId);
                br.setBookId(bookId);
                br.setBorrowDate(brD);
                br.setReturnDate(rtD);
                boolean bl = new BorrowDAOImpl().insertBorrow(br);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Insert successful");
                    //refresh Jtable
                    populateJTableWithBorrow();

                    //clear text from the textfield
                    txt_Id.setText("");
                    combo_CardCode.setSelectedIndex(-1);
                    combo_Book.setSelectedIndex(-1);
                    txt_BorrowDate.setDate(null);
                    txt_ReturnDate.setDate(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Add not successful", "Add", 2);
                }
            }
        }
    }//GEN-LAST:event_jButton_Add_ActionPerformed

    private void jButton_Edit_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Edit_ActionPerformed
        // Edit card
        List<LibraryCard> listLib = new LibraryCardDAOImpl().getCardList();
        List<Book> listBook = new BookDAOImpl().getListBook();
        String id = txt_Id.getText().trim();
        Date brD = txt_BorrowDate.getDate();
        Date rtD = txt_ReturnDate.getDate();
        LibraryCard lib = listLib.get(combo_CardCode.getSelectedIndex());
        int cardId = lib.getId();
        Book b = listBook.get(combo_Book.getSelectedIndex());
        int bookId = b.getBookId();
        // check textfield empty or not
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "This field cannot be empty", "Id", 2);
        } else if (brD == null) {
            JOptionPane.showMessageDialog(null, "This field cannot be empty", "Borrow Date", 2);
        } else if (rtD == null) {
            JOptionPane.showMessageDialog(null, "This field cannot be empty", "Return Date", 2);
        } else {
            if (brD.compareTo(rtD)>0) {
                JOptionPane.showMessageDialog(null, "Return Date must be greater than borrow date", "Return Date", 2);
            } else {
                //Calculate age from date of birth by localdate            
                Borrow br = new Borrow();
                br.setBorrowId(Integer.parseInt(id));
                br.setBookId(bookId);
                br.setCardId(cardId);
                br.setBorrowDate(brD);
                br.setReturnDate(rtD);
                boolean bl = new BorrowDAOImpl().updateBorrow(br);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Edit successful");
                    //refresh Jtable
                    populateJTableWithBorrow();

                    //clear text from the textfield
                    txt_Id.setText("");
                    combo_CardCode.setSelectedIndex(-1);
                    combo_Book.setSelectedIndex(-1);
                    txt_BorrowDate.setDate(null);
                    txt_ReturnDate.setDate(null);
                } else {
                    JOptionPane.showMessageDialog(null, "Edit not successful", "Add", 2);
                }
            }
        }
    }//GEN-LAST:event_jButton_Edit_ActionPerformed

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed
        // TODO add your handling code here:
        try {
                int id = Integer.parseInt(txt_Id.getText());
                boolean bl = new BorrowDAOImpl().deleteBorrow(id);
                if (bl) {
                    JOptionPane.showMessageDialog(this, "Delete successful");
                    //refresh Jtable
                    populateJTableWithBorrow();
                }
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showConfirmDialog(this, "Invalid Borrow id", "Error", 0);
            }
    }//GEN-LAST:event_jButton_Delete_ActionPerformed

    private void jTable_Borrow_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Borrow_MouseClicked
        // Display the selected LibraryCard
        int index =  jTable_Borrow_.getSelectedRow();
        
        //get values
        String id = jTable_Borrow_.getValueAt(index, 0).toString();
        String cardCode = jTable_Borrow_.getValueAt(index, 1).toString();
        String bookName = jTable_Borrow_.getValueAt(index, 2).toString();
        String brD = jTable_Borrow_.getValueAt(index, 3).toString();
        String rtD = jTable_Borrow_.getValueAt(index, 4).toString();
        
        //show data in textfield
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        txt_Id.setText(id);
        combo_CardCode.setSelectedItem(cardCode);
        combo_Book.setSelectedItem(bookName);
        try {
            txt_BorrowDate.setDate(sf.parse(brD));
            txt_ReturnDate.setDate(sf.parse(rtD));
        } catch (ParseException ex) {
            Logger.getLogger(ManageBorrowForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable_Borrow_MouseClicked

    private void jButton_FindById_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_FindById_ActionPerformed
        // TODO add your handling code here:
        String strId = JOptionPane.showInputDialog("Enter Id!");
        if (strId!=null && strId.length()>0) {
            try {
                int borrowId = Integer.parseInt(strId);
                Borrow br = new BorrowDAOImpl().getBorrowById(borrowId);
                if (br!=null) {
                    txt_Id.setText(br.getBorrowId()+"");
                    combo_CardCode.setSelectedItem(br.getCardCode());
                    combo_Book.setSelectedItem(br.getBookName());
                    txt_BorrowDate.setDate(br.getBorrowDate());
                    txt_ReturnDate.setDate(br.getReturnDate());
                }else{
                    JOptionPane.showMessageDialog(this, "Invalid id "+strId, "Error", 0);
                }
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showConfirmDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton_FindById_ActionPerformed

    private void combo_CardCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_CardCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_CardCodeActionPerformed

    private void combo_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_BookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_BookActionPerformed
        
    //create a function to populate the jTable with Borrow
    public void populateJTableWithBorrow(){
        SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        List<LibraryCard> listLib = new LibraryCardDAOImpl().getCardList();
        List<Book> listBook = new BookDAOImpl().getListBook();
        List<Borrow> listBorrow = new BorrowDAOImpl().getBorrowList();
        
        //Jtable column
        String [] colNames = {"ID", "Card Code", "Book", "Borrow Date", "Return Date"};
        
        //get data to jcombobox
        DefaultComboBoxModel<String> cbmCardCode = (DefaultComboBoxModel<String>) combo_CardCode.getModel();
        cbmCardCode.removeAllElements();
        DefaultComboBoxModel<String> cbmBook = (DefaultComboBoxModel<String>) combo_Book.getModel();
        cbmBook.removeAllElements();
        for (LibraryCard cardcode : listLib) {
            cbmCardCode.addElement(cardcode.getCardCode());
        }
        for (Book book : listBook) {
            cbmBook.addElement(book.getName());
        }
        //rows
        Object[][] rows = new Object[listBorrow.size()][colNames.length];
        for (int i = 0; i < listBorrow.size(); i++) {
            rows[i][0] = listBorrow.get(i).getBorrowId();
            rows[i][1] = listBorrow.get(i).getCardCode();
            rows[i][2] = listBorrow.get(i).getBookName();
            rows[i][3] = sf.format(listBorrow.get(i).getBorrowDate());
            rows[i][4] = sf.format(listBorrow.get(i).getReturnDate());
        }
        dftbl = new DefaultTableModel(rows, colNames);
        jTable_Borrow_.setModel(dftbl);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBorrowForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBorrowForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBorrowForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBorrowForm.class
.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBorrowForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_Book;
    private javax.swing.JComboBox<String> combo_CardCode;
    private javax.swing.JButton jButton_Add_;
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Edit_;
    private javax.swing.JButton jButton_FindById_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_CloseForm;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Borrow_;
    private com.toedter.calendar.JDateChooser txt_BorrowDate;
    private javax.swing.JTextField txt_Id;
    private com.toedter.calendar.JDateChooser txt_ReturnDate;
    // End of variables declaration//GEN-END:variables
}
